(() => {
  "use strict";
  const DATA_KEY = "portfolio_data_v1";
  const PASSWORD_KEY = "portfolio_admin_password_v1";
  const SESSION_KEY = "portfolio_admin_session_v1";
  const LOAD_URL = "/.netlify/functions/load-data";
  const SAVE_URL = "/.netlify/functions/save-data";
  const DEFAULTS = { site: { title: "ADAM EL IDRISSI | Web Developer", name: "ADAM EL IDRISSI", role: "Web Developer", description: "", about: "", email: "", github: "", contactStatus: "", accentColor: "#a855f7" }, skills: [], projects: [], stats: { projects: "0+", experience: "1+", focus: "Clean" } };
  let data = null;
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const clone = (v) => JSON.parse(JSON.stringify(v));
  const merge = (v) => ({ ...clone(DEFAULTS), ...(v || {}), site: { ...DEFAULTS.site, ...((v || {}).site || {}) }, stats: { ...DEFAULTS.stats, ...((v || {}).stats || {}) }, skills: Array.isArray(v?.skills) ? v.skills : [], projects: Array.isArray(v?.projects) ? v.projects : [] });
  const status = (el, text, type = "") => { if (el) { el.textContent = text; el.className = `form__status ${type}`; } };
  const hash = async (value) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))), b => b.toString(16).padStart(2, "0")).join("");
  const showAdmin = () => { $("#authScreen")?.classList.add("hidden"); $("#adminPanel")?.classList.remove("hidden"); fillForm(); };
  const showAuth = () => { $("#authScreen")?.classList.remove("hidden"); $("#adminPanel")?.classList.add("hidden"); };
  const set = (id, value) => { const el = $(id); if (el) el.value = value ?? ""; };
  function fillForm() { const s = data.site; set("#siteName", s.name); set("#siteRole", s.role); set("#siteTitle", s.title); set("#siteDesc", s.description); set("#siteAbout", s.about); set("#siteEmail", s.email); set("#siteGithub", s.github); set("#siteStatus", s.contactStatus); set("#statProjects", data.stats.projects); set("#statExp", data.stats.experience); set("#statFocus", data.stats.focus); set("#skillsInput", data.skills.join(", ")); set("#accentColor", s.accentColor); renderProjects(); }
  function readForm() { data.site = { ...data.site, name: $("#siteName")?.value.trim(), role: $("#siteRole")?.value.trim(), title: $("#siteTitle")?.value.trim(), description: $("#siteDesc")?.value.trim(), about: $("#siteAbout")?.value.trim(), email: $("#siteEmail")?.value.trim(), github: $("#siteGithub")?.value.trim(), contactStatus: $("#siteStatus")?.value.trim(), accentColor: $("#accentColor")?.value }; data.stats = { projects: $("#statProjects")?.value.trim(), experience: $("#statExp")?.value.trim(), focus: $("#statFocus")?.value.trim() }; data.skills = $("#skillsInput")?.value.split(",").map(x => x.trim()).filter(Boolean) || []; data.projects = $$(".project-item").map((item, i) => ({ id: $(".project-id", item)?.value || `project-${Date.now()}-${i}`, title: $(".project-title", item)?.value.trim(), description: $(".project-desc", item)?.value.trim(), tags: $(".project-tags", item)?.value.split(",").map(x => x.trim()).filter(Boolean), featured: $(".project-featured", item)?.checked, icon: $(".project-icon", item)?.value || "fa-code", demoUrl: $(".project-demo", item)?.value.trim() || "#", repoUrl: $(".project-repo", item)?.value.trim() || "" })); }
  function renderProjects() { const list = $("#projectsList"), template = $("#projectTemplate"); if (!list || !template) return; list.innerHTML = ""; data.projects.forEach(p => { const fragment = template.content.cloneNode(true); const item = $(".project-item", fragment); $(".project-id", fragment).value = p.id; $(".project-title", fragment).value = p.title || ""; $(".project-desc", fragment).value = p.description || ""; $(".project-tags", fragment).value = (p.tags || []).join(", "); $(".project-featured", fragment).checked = !!p.featured; $(".project-icon", fragment).value = p.icon || "fa-code"; $(".project-demo", fragment).value = p.demoUrl || "#"; $(".project-repo", fragment).value = p.repoUrl || ""; $(".project-item__title", fragment).textContent = p.title || "Untitled project"; list.appendChild(fragment); }); }
  async function readJsonResponse(response) { const text = await response.text(); let body = null; try { body = text ? JSON.parse(text) : null; } catch { const detail = text.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim().slice(0, 180); const error = new Error(detail || `Request failed (${response.status})`); error.status = response.status; throw error; } if (!response.ok) { const error = new Error(body?.error || `Request failed (${response.status})`); error.status = response.status; throw error; } return body; }
  async function requestJson(url, options = {}) { const fallback = url.startsWith(LOAD_URL) ? `/api/load-data${url.slice(LOAD_URL.length)}` : url.startsWith(SAVE_URL) ? "/api/save-data" : null; try { return await readJsonResponse(await fetch(url, { cache: "no-store", ...options })); } catch (error) { if (!fallback || error.status !== 404) throw error; return readJsonResponse(await fetch(fallback, { cache: "no-store", ...options })); } }
  async function load() { try { const body = await requestJson(`${LOAD_URL}?t=${Date.now()}`); if (body.data?.site) { data = merge(body.data); localStorage.setItem(DATA_KEY, JSON.stringify(data)); return; } } catch (error) { console.error("[v0] admin load failed", error); } data = merge(JSON.parse(localStorage.getItem(DATA_KEY) || "null")); }
  document.addEventListener("DOMContentLoaded", async () => { await load(); const configured = localStorage.getItem(PASSWORD_KEY); $("#setupForm")?.classList.toggle("hidden", !!configured); $("#loginForm")?.classList.toggle("hidden", !configured); if (localStorage.getItem(SESSION_KEY) === "authenticated") showAdmin();
    $("#setupForm")?.addEventListener("submit", async e => { e.preventDefault(); const a = $("#setupPass").value, b = $("#setupPass2").value; if (a.length < 4 || a !== b) return status($("#setupStatus"), "Passwords must match and be at least 4 characters.", "error"); localStorage.setItem(PASSWORD_KEY, await hash(a)); localStorage.setItem(SESSION_KEY, "authenticated"); showAdmin(); });
    $("#loginForm")?.addEventListener("submit", async e => { e.preventDefault(); if (await hash($("#loginPass").value) !== localStorage.getItem(PASSWORD_KEY)) return status($("#loginStatus"), "Incorrect password.", "error"); localStorage.setItem(SESSION_KEY, "authenticated"); showAdmin(); });
    $("#logoutBtn")?.addEventListener("click", () => { localStorage.removeItem(SESSION_KEY); showAuth(); }); $("#previewBtn")?.addEventListener("click", () => window.open("../", "_blank", "noopener,noreferrer")); $("#resetBtn")?.addEventListener("click", () => { if (confirm("Reset all content to defaults?")) { data = merge(DEFAULTS); fillForm(); } }); $("#addProjectBtn")?.addEventListener("click", () => { readForm(); data.projects.push({ id: `project-${Date.now()}`, title: "New Project", description: "", tags: [], featured: false, icon: "fa-code", demoUrl: "#", repoUrl: "" }); renderProjects(); }); $("#saveBtn")?.addEventListener("click", async e => { const button = e.currentTarget; button.disabled = true; try { readForm(); const body = await requestJson(SAVE_URL, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(data) }); if (!body.data?.site) throw new Error("The server returned invalid portfolio data"); data = merge(body.data); localStorage.setItem(DATA_KEY, JSON.stringify(data)); status($("#saveStatus"), "Changes saved to Supabase and are live on every device.", "success"); } catch (error) { console.error("[v0] admin save failed", error); status($("#saveStatus"), error.message || "Save failed. Confirm the site is deployed with Netlify Functions enabled.", "error"); } finally { button.disabled = false; } });
    $("#projectsList")?.addEventListener("click", e => { const button = e.target.closest("button[data-action]"); if (!button) return; const item = button.closest(".project-item"); if (button.dataset.action === "delete") item.remove(); if (button.dataset.action === "toggle") $(".project-item__content", item)?.classList.toggle("collapsed"); }); $$(".tab").forEach(tab => tab.addEventListener("click", () => { $$(".tab").forEach(t => t.classList.toggle("active", t === tab)); $$(".tab-content").forEach(c => c.classList.toggle("active", c.id === `tab-${tab.dataset.tab}`)); }));
  });
})();
